const actionTypes = {
  APP_INIT: "APP_INIT",
  CREATE_DEPLOYMENT_SUCCESS: "CREATE_DEPLOYMENT_SUCCESS",
  HANDLE_ERROR: "HANDLE_ERROR",
  GET_ALL_DEPLOYMENTS_SUCCESS: "GET_ALL_DEPLOYMENTS_SUCCESS",
  DELETE_DEPLOYMENT_SUCCESS: "DELETE_DEPLOYMENT_SUCCESS",
};

export default actionTypes;
